server:
  port: 8086
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.44.131:9300
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
        host: 192.168.44.131
        virtual-host: /leyou
        username: leyou
        password: leyou
        template:
          exchange: LEYOU.ITEM.EXCHANGE
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
